spring.application.name=basic-payment-service

spring.datasource.url=jdbc:h2:mem:payments;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.open-in-view=false
spring.jpa.defer-datasource-initialization=true

spring.sql.init.mode=always

spring.h2.console.enabled=true
